services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: "1000:1000"
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./data/jellyfin/config:/config
      - ./data/jellyfin/cache:/cache
      - /mnt/storage/media:/media:ro
    group_add:
      - "992" # render group
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128 # use system GPU
    extra_hosts:
      - 'host.docker.internal:host-gateway' # necessary for docker healthcheck to pass if running in host network mode
