services:
  jellyfin:
    image: jellyfin/jellyfin:10.10.7
    container_name: jellyfin
    user: "1000:1000"
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./data/jellyfin/config:/config
      - ./data/jellyfin/cache:/cache
      - /mnt/storage/media:/media:ro
    group_add:
      - "992" # render group
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128 # use system GPU
    extra_hosts:
      - "host.docker.internal:host-gateway" # necessary for docker healthcheck to pass if running in host network mode

  slskd:
    image: slskd/slskd:0.24.0
    container_name: slskd
    user: "1000:1000"
    restart: unless-stopped
    ports:
      - 5030:5030/tcp
      - 5031:5031/tcp
      - 50300:50300/tcp
    environment:
      - SLSKD_SLSK_USERNAME=${SLSKD_SLSK_USERNAME}
      - SLSKD_SLSK_PASSWORD=${SLSKD_SLSK_PASSWORD}
      - SLSKD_USERNAME=${SLSKD_USERNAME}
      - SLSKD_PASSWORD=${SLSKD_PASSWORD}
      - SLSKD_SHARED_DIR=/music
      - SLSKD_DOWNLOADS_DIR=/downloads/complete
      - SLSKD_INCOMPLETE_DIR=/downloads/incomplete
    volumes:
      - ./data/slskd:/app:rw
      - /mnt/storage/media/music:/music:ro
      - /mnt/storage/media/slskd:/downloads

  homer:
    image: b4bz/homer:v25.08.1
    container_name: homer
    user: "1000:1000"
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - INIT_ASSETS=1
    volumes:
      - ./configs/homer:/www/assets:ro

  registry:
    image: registry:3.0.0
    container_name: registry
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - OTEL_TRACES_EXPORTER=none
      - REGISTRY_LOG_LEVEL=info # default: debug
    volumes:
      - ./data/registry:/var/lib/registry

  scheduler:
    image: mcuadros/ofelia:0.3.18
    container_name: scheduler
    restart: unless-stopped
    environment:
      - TZ=Europe/Madrid
    volumes:
      - ./configs/scheduler/ofelia.ini:/etc/ofelia/config.ini:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - registry
    command: daemon --config=/etc/ofelia/config.ini

  glances:
    image: nicolargo/glances:latest-full
    container_name: glances
    pid: host
    privileged: true # network interface stats
    restart: unless-stopped
    network_mode: "host"
    environment:
      - GLANCES_OPT=-w # run the container in Web server mode
      - TZ=Europe/Madrid
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/os-release:/etc/os-release:ro # display host OS detail instead of container's
      - /mnt/storage:/mnt/storage:ro

  syncthing:
    image: syncthing/syncthing:2.0.11
    container_name: syncthing
    user: "1000:1000"
    restart: unless-stopped
    environment:
      - TZ=Europe/Madrid
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    volumes:
      - ./data/syncthing:/var/syncthing
      - /mnt/storage/synced:/synced

  kopia:
    image: kopia/kopia:0.22
    hostname: hp-minipc
    container_name: kopia
    user: "1000:1000"
    restart: unless-stopped
    ports:
      - 51515:51515
    command:
      - server
      - start
      - --disable-csrf-token-checks
      - --insecure
      - --address=0.0.0.0:51515
      - --server-username=admin
      - --server-password=${KOPIA_SERVER_PASSWORD}
    environment:
      - KOPIA_PASSWORD=${KOPIA_PASSWORD}
      - TZ=Europe/Madrid
    volumes:
      - ./data/kopia/config:/app/config
      - ./data/kopia/cache:/app/cache
      - ./data/kopia/logs:/app/logs
      - /home/carlos/hp-minipc:/source/hp-minipc:ro
      - /mnt/storage:/source/storage:ro

  radarr:
    image: lscr.io/linuxserver/radarr:5.28.0
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "7878:7878"
    volumes:
      - ./data/radarr:/config
      - /mnt/storage:/data

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:5.1.2
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=8081
    ports:
      - "8081:8081"
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      - ./data/qbittorrent:/config
      - /mnt/storage:/data

  audiodeck:
    image: casantosmu/audiodeck:latest
    container_name: audiodeck
    user: "1000:1000"
    restart: unless-stopped
    ports:
      - "4747:4747"
    volumes:
      - /mnt/storage/media:/media:ro
