services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: "1000:1000"
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./data/jellyfin/config:/config
      - ./data/jellyfin/cache:/cache
      - /mnt/storage/media:/media:ro
    group_add:
      - "992" # render group
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128 # use system GPU
    extra_hosts:
      - 'host.docker.internal:host-gateway' # necessary for docker healthcheck to pass if running in host network mode

  slskd:
    image: slskd/slskd
    container_name: slskd
    user: "1000:1000"
    restart: unless-stopped
    ports:
      - 5030:5030/tcp
      - 5031:5031/tcp
      - 50300:50300/tcp
    environment:
      - SLSKD_SLSK_USERNAME=${SLSKD_SLSK_USERNAME}
      - SLSKD_SLSK_PASSWORD=${SLSKD_SLSK_PASSWORD}
      - SLSKD_USERNAME=${SLSKD_USERNAME}
      - SLSKD_PASSWORD=${SLSKD_PASSWORD}
      - SLSKD_SHARED_DIR=/music
      - SLSKD_DOWNLOADS_DIR=/downloads/complete
      - SLSKD_INCOMPLETE_DIR=/downloads/incomplete
    volumes:
      - ./data/slskd:/app:rw
      - /mnt/storage/media/music:/music:ro
      - /mnt/storage/media/slskd:/downloads

  homer:
    image: b4bz/homer
    container_name: homer
    user: "1000:1000"
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - INIT_ASSETS=1
    volumes:
      - ./configs/homer:/www/assets:ro

  registry:
    image: registry
    container_name: registry
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - OTEL_TRACES_EXPORTER=none
      - REGISTRY_LOG_LEVEL=info # default: debug
    volumes:
      - ./data/registry:/var/lib/registry

  scheduler:
    image: mcuadros/ofelia
    container_name: scheduler
    restart: unless-stopped
    environment:
      - TZ=Europe/Madrid
    volumes:
      - ./configs/scheduler/ofelia.ini:/etc/ofelia/config.ini:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - registry
    command: daemon --config=/etc/ofelia/config.ini

  portainer:
    image: portainer/portainer-ee
    container_name: portainer
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - ./data/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro

  glances:
    image: nicolargo/glances:latest-full
    container_name: glances
    pid: host
    privileged: true # network interface stats
    restart: unless-stopped
    network_mode: "host"
    environment:
      - GLANCES_OPT=-w # run the container in Web server mode
      - TZ=Europe/Madrid
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/os-release:/etc/os-release:ro # display host OS detail instead of container's
      - /mnt/storage:/mnt/storage:ro
